#!/bin/bash -e

##**************************************************************************
## Copyright (C) 2023-2025 Sergey Kovalenko <seryoga.engineering@gmail.com>
## SPDX-License-Identifier: MIT
##**************************************************************************
VERSION=1.0.7

function display_help () {
    echo "Usage: $0 [OPTION]" >&2
    echo "Available options:"
    echo "    -h, --help            display help and exit"
    echo "    -v, --version         display version"
    echo
    echo "This tool serves as One-click update button for Linux users."
    echo "It performs the following actions:"
    echo "- updates mirrorlist (Arch Linux)"
    echo "- checks for updates"
    echo "- performs update"
    echo "- removes invalid/unsupported packages"
    echo "Note: ipinfo.io service is used to determine the country code for mirrorlist request."
    exit
}

function display_version () {
    echo "Simple System Update version $VERSION"
    echo "Copyright (C) 2023-2025 Sergey Kovalenko <seryoga.engineering@gmail.com>"
    echo "This is free software under MIT license."
    echo "In case of issue please report to <https://github.com/SeryogaBrigada/SimpleSystemUpdate/issues>"
    exit
}

# Process arguments
while :
do
    case "$1" in
        -h | --help)
            display_help
            exit 0
            ;;
        -v | --version)
            display_version
            exit 0
            ;;
        -*)
            echo "Error: Unknown option: $1" >&2
            display_help
            exit 1
            ;;
        *)  # No options
            break
            ;;
    esac
done

# Update Flatpak
if which flatpak >/dev/null 2>&1; then
    flatpak update --noninteractive
fi

# Update Snap
if which snap >/dev/null 2>&1; then
    sudo snap refresh
fi

# Ubuntu/Debian
if which apt >/dev/null 2>&1; then
    sudo apt update
    sudo apt dist-upgrade -y
    sudo apt autoremove --purge -y
    sudo apt clean
    exit
fi

# Arch Linux
function get_country_code () {
    # Fallback country code if the ipinfo.io service is unavailable
    local COUNTRY=US

    # Get the ISP country from ipinfo.io service
    local FOUND_COUNTRY=$(curl -s ipinfo.io | jq -r '.country')

    if [ ! -z $FOUND_COUNTRY ]; then
        COUNTRY=$FOUND_COUNTRY
    fi

    echo $COUNTRY
}

if which pacman >/dev/null 2>&1; then
    if [[ -f /etc/pacman.d/mirrorlist ]]; then
        if grep -q archlinux /etc/pacman.d/mirrorlist; then
            # Remove the .pacnew file since the mirrorlist will be updated on the next stage
            [[ -f /etc/pacman.d/mirrorlist.pacnew ]] && sudo rm /etc/pacman.d/mirrorlist.pacnew;

            # Update mirrorlist for current country
            SERVER_COUNTRY=$(get_country_code)
            echo "Update mirrorlist for $SERVER_COUNTRY"
            curl -s "https://archlinux.org/mirrorlist/?country=${SERVER_COUNTRY}&protocol=https&use_mirror_status=on" \
                | sed -e 's/^#Server/Server/' -e '/^#/d' \
                | rankmirrors -n 5 - \
                | sudo tee /etc/pacman.d/mirrorlist.tmp
            # Check correctness
            if grep -q archlinux /etc/pacman.d/mirrorlist.tmp; then
                echo "Operation successful, updating mirrorlist"
                sudo mv /etc/pacman.d/mirrorlist.tmp /etc/pacman.d/mirrorlist
            else
                echo "Mirrorlist update failed! Continue with the old one."
                [[ -f /etc/pacman.d/mirrorlist.tmp ]] && sudo rm /etc/pacman.d/mirrorlist.tmp;
            fi
        elif grep -q manjaro /etc/pacman.d/mirrorlist; then
            # Update mirrorlist for Manjaro
            sudo pacman-mirrors --fasttrack 5
        fi
    fi

    # Update EndeavourOS mirrorlist if the new one is present
    if [[ -f /etc/pacman.d/endeavouros-mirrorlist.pacnew ]] then
        sudo mv /etc/pacman.d/endeavouros-mirrorlist.pacnew /etc/pacman.d/endeavouros-mirrorlist
    fi

    # Update makepkg.conf if the new one is present
    if [[ -f /etc/makepkg.conf.pacnew ]]; then
        sudo mv /etc/makepkg.conf.pacnew /etc/makepkg.conf
        # Apply optimal parameters
        sudo sed -i 's|-march=x86-64 -mtune=generic|-march=native -mtune=native|g' /etc/makepkg.conf
        sudo sed -i 's|#MAKEFLAGS="-j2"|MAKEFLAGS="-j$(nproc)"|g' /etc/makepkg.conf
        sudo sed -i "s|PKGEXT='.pkg.tar.xz'|PKGEXT='.pkg.tar.zst'|g" /etc/makepkg.conf
        sudo sed -i "s|SRCEXT='.src.tar.gz'|SRCEXT='.src.tar.zst'|g" /etc/makepkg.conf
    fi

    # Update system packages first
    sudo pacman -Syyu --noconfirm

    # Check yay is installed and works correctly
    if yay --version >/dev/null 2>&1; then
        yay -Syu --noconfirm --removemake --editmenu=false --diffmenu=false --cleanmenu=false
        yay -Yc --noconfirm
    fi

    exit
fi

echo "Unsupported package manager"
exit 1
