#!/bin/bash -e

##**************************************************************************
## MIT License
##
## Copyright (C) 2023-2024 Sergey Kovalenko <seryoga.engineering@gmail.com>
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sub-license, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.
##**************************************************************************
VERSION=1.0.0

function display_help () {
    echo "Usage: $0 [OPTION]" >&2
    echo "Available options:"
    echo "    -h, --help            display help and exit"
    echo "    -v, --version         display version"
    echo
    echo "This tool serves as One-click update button for Linux users."
    echo "It performs the following actions:"
    echo "- updates mirrorlist (Arch Linux)"
    echo "- checks for updates"
    echo "- performs update"
    echo "- removes invalid/unsupported packages"
    echo "Note: ipinfo.io service is used to determine the country code for mirrorlist request."
    exit
}

function display_version () {
    echo "Simple System Update version $VERSION"
    echo "Copyright (C) 2023-2024 Sergey Kovalenko <seryoga.engineering@gmail.com>"
    echo "This is free software under MIT license."
    echo "In case of issue please report to <https://github.com/SeryogaBrigada/SimpleSystemUpdate/issues>"
    exit
}

# Process arguments
while :
do
    case "$1" in
        -h | --help)
            display_help
            exit 0
            ;;
        -v | --version)
            display_version
            exit 0
            ;;
        -*)
            echo "Error: Unknown option: $1" >&2
            display_help
            exit 1
            ;;
        *)  # No options
            break
            ;;
    esac
done

# Update Flatpak
if which flatpak >/dev/null 2>&1; then
    flatpak update --noninteractive
fi

# Update Snap
if which snap >/dev/null 2>&1; then
    sudo snap refresh
fi

# Ubuntu/Debian
if which apt >/dev/null 2>&1; then
    sudo apt update
    sudo apt dist-upgrade -y
    sudo apt autoremove --purge -y
    sudo apt clean
    exit
fi

# Arch Linux
function get_country_code () {
    # Fallback country code if the ipinfo.io service is unavailable
    COUNTRY=US

    # Use ipinfo.io response
    if ping -c 1 ipinfo.io >/dev/null 2>&1; then
        COUNTRY=$(curl ipinfo.io | grep country | awk '{print $2}' | sed 's/[",]//g')
    fi

    echo $COUNTRY
}

if which pacman >/dev/null 2>&1; then
    if [[ -f /etc/pacman.d/mirrorlist ]]; then
        if grep -q archlinux /etc/pacman.d/mirrorlist; then
            # Update mirrorlist for Arch Linux
            SERVER_COUNTRY=$(get_country_code)
            echo "Update mirrorlist for $SERVER_COUNTRY"

            curl -s "https://archlinux.org/mirrorlist/?country=${SERVER_COUNTRY}&protocol=https&use_mirror_status=on" \
                | sed -e 's/^#Server/Server/' -e '/^#/d' \
                | rankmirrors -n 5 - \
                | sudo tee /etc/pacman.d/mirrorlist.tmp
            # Check correctness
            if grep -q archlinux /etc/pacman.d/mirrorlist.tmp; then
                echo "Operation successful, updating mirrorlist"
                sudo rm /etc/pacman.d/mirrorlist
                sudo mv /etc/pacman.d/mirrorlist.tmp /etc/pacman.d/mirrorlist
            else
                echo "Unable to update mirrorlist! Continue with the current one."
                [[ -f /etc/pacman.d/mirrorlist.tmp ]] && sudo rm /etc/pacman.d/mirrorlist.tmp;
            fi
        elif grep -q manjaro /etc/pacman.d/mirrorlist; then
            # Update mirrorlist for Manjaro
            sudo pacman-mirrors --fasttrack 5
        fi
    fi

    if which yay >/dev/null 2>&1; then
        yay -Syyu --noconfirm --needed --removemake --editmenu=false --diffmenu=false --cleanmenu=false
        yay -Yc --noconfirm
    else
        sudo pacman -Syyu --noconfirm
    fi

    exit
fi

echo "Unsupported package manager"
exit 1
